apiVersion: v1
kind: Namespace
metadata:
  name: pubsub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pubsub-ksa
  namespace: pubsub
  annotations:
    iam.gke.io/gcp-service-account: serviceAccount:pubsub-sa@<<PROJECT_ID>>.iam.gserviceaccount.com
