# [START gke_guestbook_redis_leader_service_service_redis_leader]
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend
# [END gke_guestbook_redis_leader_service_service_redis_leader]
